//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherBasicInfo
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Collage { get; set; }
        public string Major { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Photo { get; set; }
        public string Course1 { get; set; }
        public string Course2 { get; set; }
        public string Course3 { get; set; }
        public string Course4 { get; set; }
        public string PATP { get; set; }
        public string HightestDegree { get; set; }
        public string GraduationSchool { get; set; }
        public string IndividualResume { get; set; }
        public string IdentityType { get; set; }
    }
}
