//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentSyllabusDetail
    {
        public int id { get; set; }
        public Nullable<int> CourseCode { get; set; }
        public string Chapter { get; set; }
        public string KnowledgePoint { get; set; }
        public string Memorization { get; set; }
        public string Comprehend { get; set; }
        public string Apply { get; set; }
        public string SampleQuestion { get; set; }
    }
}
