//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperimentSyllabusDetail
    {
        public int id { get; set; }
        public Nullable<int> CourseCode { get; set; }
        public Nullable<int> ExperimentCode { get; set; }
        public string ExperimentName { get; set; }
        public Nullable<int> ExperimentPeriod { get; set; }
        public string ExperimentType { get; set; }
        public string ExperimentAim { get; set; }
        public string ExperimentClaim { get; set; }
        public string ExperimentTheory { get; set; }
        public string ExperimentStep { get; set; }
        public string ExperimentEquipment { get; set; }
    }
}
