//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentBasicInfo
    {
        public int id { get; set; }
        public string StudentNo { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Major { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Photo { get; set; }
        public string ZipCope { get; set; }
        public string Contacts { get; set; }
        public string ConttactTel { get; set; }
    }
}
