//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherBasicInfo
    {
        public int Id { get; set; }
        public string EmpNo { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Collage { get; set; }
        public string Major { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Mail { get; set; }
        public string Photo { get; set; }
        public string Course1 { get; set; }
        public string Course2 { get; set; }
        public string Course3 { get; set; }
        public string Course4 { get; set; }
        public string PATP { get; set; }
        public string HightestDegree { get; set; }
        public string GraduationSchool { get; set; }
        public string IndividualResume { get; set; }
        public string IdentityType { get; set; }
    }
}
