//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teaching.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachingSyllabusDetail
    {
        public int id { get; set; }
        public Nullable<int> CourseCode { get; set; }
        public string CourseContent { get; set; }
        public Nullable<int> TheoreticalLessons { get; set; }
        public Nullable<int> ExperimentLessons { get; set; }
        public Nullable<int> ExerciseLessons { get; set; }
        public Nullable<int> ComputerLessons { get; set; }
        public string TeachRequirement { get; set; }
        public string Synopsis { get; set; }
        public string TeachKeyPoint { get; set; }
        public string LessonReview { get; set; }
        public string TeachingAims { get; set; }
        public string Title { get; set; }
        public Nullable<int> SerialNo { get; set; }
    }
}
